### PR TITLE
Example fixed to use https by default

### PR DESCRIPTION
**Pull request by pruser**

### CODE REVIEW

**Comment by HeeL** [comment]
Can you please also add scheme prop in prop table in this README?

**Comment by pruser** [comment]
Sure, I can pass it as a prop to the example component, but isn't it redundant?
It's quite unlikely that somebody would use different schemes to load the script in one project.
What's your opinion?

**Comment by HeeL** [comment]
Thank you, merging this...

**Comment by HeeL** [comment]
@pruser we don't use this prop in our case, I can imagine that someone prefer to use https even though the website is on http for some reason

**Pull request merged**
